const tools = [
  {"name": "ROAS Calculator", "url": "roas.html", "keywords": "marketing roas return ad spend advertising revenue break even"},
  {"name": "Marketing ROI Calculator", "url": "marketing-roi.html", "keywords": "marketing roi return investment campaign profit cost"},
  {"name": "Customer Acquisition Cost Calculator", "url": "cac.html", "keywords": "marketing cac customer acquisition cost sales spend"},
  {"name": "Customer Lifetime Value Calculator", "url": "clv.html", "keywords": "marketing clv ltv lifetime customer value retention revenue margin"},
  {"name": "Conversion Rate Calculator", "url": "conversion-rate.html", "keywords": "marketing conversion rate visitors leads sales ecommerce"},
  {"name": "CPC Calculator", "url": "cpc.html", "keywords": "marketing cpc cost per click advertising ads"},
  {"name": "CPM Calculator", "url": "cpm.html", "keywords": "marketing cpm cost per thousand impressions advertising"},
  {"name": "Email Marketing Calculator", "url": "email-marketing.html", "keywords": "marketing email open rate ctr click conversion revenue"},

  {"name": "Car Finance Calculator", "url": "car-finance.html", "keywords": "automotive car finance apr monthly payment vehicle loan"},
  {"name": "MPG to L/100km Converter", "url": "mpg-converter.html", "keywords": "automotive mpg imperial uk litres 100km fuel economy"},
  {"name": "EV Charging Cost Calculator", "url": "ev-charging-cost.html", "keywords": "automotive electric ev charging kwh electricity cost"},
  {"name": "Journey Cost Calculator", "url": "journey-cost.html", "keywords": "automotive journey compare petrol diesel electric ev cost"},
  {"name": "Mileage Reimbursement Calculator", "url": "mileage-reimbursement.html", "keywords": "automotive hmrc mileage business reimbursement 55p 25p"},
  {"name": "Tyre Size Calculator", "url": "tyre-size.html", "keywords": "automotive tyre tire size diameter circumference speedometer"},
  {"name": "Car Depreciation Calculator", "url": "car-depreciation.html", "keywords": "automotive car depreciation future value vehicle"},

  {"name": "Recipe Scaler", "url": "recipe-scaler.html", "keywords": "cooking kitchen recipe scale servings ingredients"},
  {"name": "Cups to Grams Converter", "url": "cups-to-grams.html", "keywords": "cooking kitchen cups grams tablespoons teaspoons flour sugar"},
  {"name": "Oven Temperature Converter", "url": "oven-temperature.html", "keywords": "cooking kitchen oven temperature celsius fahrenheit fan gas mark"},
  {"name": "Cooking Time Calculator", "url": "cooking-time.html", "keywords": "cooking kitchen time weight portion"},
  {"name": "Portion Calculator", "url": "portion-calculator.html", "keywords": "cooking kitchen portions servings people pasta rice potatoes"},
  {"name": "Baking Pan Converter", "url": "baking-pan.html", "keywords": "cooking kitchen baking pan tin cake round square rectangle"},
  {"name": "Macro Calculator", "url": "macro-calculator.html", "keywords": "health macros protein carbs fat calories nutrition"},
  {"name": "Protein Intake Calculator", "url": "protein-intake.html", "keywords": "health protein grams bodyweight weight nutrition"},
  {"name": "Water Intake Calculator", "url": "water-intake.html", "keywords": "health water hydration fluid glasses litres"},
  {"name": "Walking Calories Calculator", "url": "walking-calories.html", "keywords": "health walking calories burn met weight exercise"},
  {"name": "Exercise Calories Calculator", "url": "exercise-calories.html", "keywords": "gym fitness exercise calories workout met activity"},
  {"name": "Barbell Weight Calculator", "url": "barbell-weight.html", "keywords": "gym fitness barbell plates weight lifting"},
  {"name": "1-Rep Max Calculator", "url": "one-rep-max.html", "keywords": "gym fitness one rep max 1rm strength lifting"},
  {"name": "Plate Loading Calculator", "url": "plate-loading.html", "keywords": "gym fitness barbell plates loading weight"},
  {"name": "Treadmill Pace Calculator", "url": "treadmill-pace.html", "keywords": "gym fitness treadmill pace speed running"},
  {"name": "Running Pace Calculator", "url": "running-pace.html", "keywords": "gym fitness running pace speed distance time"},
  {"name": "Training Volume Calculator", "url": "training-volume.html", "keywords": "gym fitness training volume sets reps weight lifting"},
  {"name": "Strength Ratio Calculator", "url": "strength-ratio.html", "keywords": "gym fitness strength ratio bodyweight lift"},
  {"name": "Break-Even Calculator", "url": "break-even.html", "keywords": "business break even fixed variable costs sales units"},
  {"name": "Hourly Rate to Salary Calculator", "url": "hourly-salary.html", "keywords": "money hourly rate salary annual weekly monthly pay"},
  {"name": "Tip Calculator & Bill Splitter", "url": "tip.html", "keywords": "travel tip gratuity bill split restaurant"},
  {"name": "Darts Checkout Calculator", "url": "darts-checkout.html", "keywords": "sports darts checkout finish double out"},
  {"name": "Darts Average Calculator", "url": "darts-average.html", "keywords": "sports darts three dart average"},
  {"name": "Football Points Calculator", "url": "football-points.html", "keywords": "sports football soccer league points wins draws"},
  {"name": "Race Time Predictor", "url": "race-time.html", "keywords": "sports running race 5k 10k half marathon marathon prediction"},
  {"name": "Cycling Speed Calculator", "url": "cycling-speed.html", "keywords": "sports cycling bike speed distance time"},
  {"name": "Golf Handicap Differential", "url": "golf-differential.html", "keywords": "sports golf handicap differential slope course rating"},
  {"name": "Key & Scale Finder", "url": "key-scale.html", "keywords": "music key scale notes major minor modes"},
  {"name": "Chord Finder", "url": "chord-finder.html", "keywords": "music chord notes major minor seventh"},
  {"name": "Chord Transposer", "url": "chord-transposer.html", "keywords": "music transpose chords key semitones"},
  {"name": "Note Frequency Calculator", "url": "note-frequency.html", "keywords": "music note frequency hz tuning a4"},
  {"name": "Guitar Fret Note Finder", "url": "guitar-fretboard.html", "keywords": "guitar fretboard string fret note tuning"},
  {"name": "Tempo & Delay Calculator", "url": "tempo-delay.html", "keywords": "music bpm tempo delay milliseconds dotted triplet"},
  {"name": "Mortgage Calculator", "url": "mortgage.html"},
  {"name": "Mortgage Overpayment", "url": "mortgage-overpayment.html"},
  {"name": "Stamp Duty Calculator", "url": "stamp-duty.html"},
  {"name": "Loan Repayment", "url": "loan.html"},
  {"name": "LTV Calculator", "url": "ltv.html"},
  {"name": "UK Take-Home Pay", "url": "salary.html"},
  {"name": "Savings Calculator", "url": "savings.html"},
  {"name": "Savings Goal", "url": "savings-goal.html"},
  {"name": "Compound Interest", "url": "compound-interest.html"},
  {"name": "Simple Interest", "url": "simple-interest.html"},
  {"name": "Fuel Cost Calculator", "url": "fuel.html"},
  {"name": "Running Pace", "url": "pace.html"},
  {"name": "Unit Converter", "url": "unit-converter.html"},
  {"name": "Days Between Dates", "url": "days-between-dates.html"},
  {"name": "Travel Time Calculator", "url": "travel-time.html"},
  {"name": "Fuel Economy Converter", "url": "fuel-economy.html"},
  {"name": "Discount Calculator", "url": "discount.html"},
  {"name": "Area Calculator", "url": "area.html"},
  {"name": "Paint Calculator", "url": "paint.html"},
  {"name": "Flooring Calculator", "url": "flooring.html"},
  {"name": "BMI Calculator", "url": "bmi.html"},
  {"name": "Calorie Calculator", "url": "calorie-calculator.html", "keywords": "calories calorie needs maintenance tdee bmr weight loss gain activity energy"},
  {"name": "Age Calculator", "url": "age.html"},
  {"name": "BMR Calculator", "url": "bmr.html"},
  {"name": "Waist-to-Height Ratio", "url": "waist-height.html"},
  {"name": "Percentage Calculator", "url": "percentage.html"},
  {"name": "Percentage Change", "url": "percentage-change.html"},
  {"name": "Average Calculator", "url": "average.html"},
  {"name": "Grade Calculator", "url": "grade.html"},
  {"name": "Ratio Calculator", "url": "ratio.html"},
  {"name": "Fraction Simplifier", "url": "fraction.html"},
  {"name": "Scientific Calculator", "url": "scientific.html"},
  {"name": "VAT Calculator", "url": "vat.html"},
  {"name": "Profit Margin", "url": "profit-margin.html"},
  {"name": "Markup Calculator", "url": "markup.html"},
  {"name": "Ceiling Tile Calculator", "url": "ceiling-tile.html", "keywords": "ceiling tiles suspended ceiling grid main tee cross tee"},
  {"name": "MF Ceiling Calculator", "url": "mf-ceiling.html", "keywords": "mf ceiling suspended ceiling drylining mf5 mf6 mf7"},
  {"name": "Plasterboard Calculator", "url": "plasterboard.html"},
  {"name": "Metal Stud Partition Calculator", "url": "metal-stud-partition.html"},
  {"name": "Insulation Calculator", "url": "insulation.html"},
  {"name": "Brick & Block Calculator", "url": "brick-block.html"},
  {"name": "Concrete Calculator", "url": "concrete.html"},
  {"name": "Screed Calculator", "url": "screed.html"},
  {"name": "U-Value Calculator", "url": "u-value.html", "keywords": "u value u-value thermal insulation heat loss construction wall roof floor"},
  {"name": "Word Finder", "url": "word-finder.html"},
  {"name": "Word Counter", "url": "word-counter.html"},
  {"name": "Reading Time Calculator", "url": "reading-time.html"},
  {"name": "Speaking Time Calculator", "url": "speaking-time.html"},
  {"name": "Reading Level Calculator", "url": "reading-level.html"}
];
const input=document.getElementById("searchInput"),box=document.getElementById("suggestions");
function render(q=""){const m=tools.filter(t=>((t.name+" "+(t.keywords||"")).toLowerCase().includes(q.toLowerCase()))).slice(0,7);if(!q||!m.length){box.hidden=true;box.innerHTML="";return}box.innerHTML=m.map(t=>`<a href="${t.url}">${t.name}</a>`).join("");box.hidden=false}
input.addEventListener("input",e=>render(e.target.value.trim()));
document.addEventListener("click",e=>{if(!e.target.closest(".search"))box.hidden=true});
document.getElementById("toolSearch").addEventListener("submit",e=>{e.preventDefault();const q=input.value.trim().toLowerCase(),hit=tools.find(t=>((t.name+" "+(t.keywords||"")).toLowerCase().includes(q)));if(hit)location.href=hit.url;else render(input.value.trim())});
